AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Serverless WordPress texturize function (ZIP build, AL2 + Bref PHP-FPM layer)'

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: zip
    Properties:
      FunctionName: wptexturize
      Description: 'Formats titles/links via Lambda'
      CodeUri: .
      Handler: index.php
      Runtime: provided.al2
      Timeout: 30        # API Gateway max timeout is 30s
      MemorySize: 2048   # adjust for PHP performance
      Layers:
        # Bref’s official PHP-FPM layer (x86_64, us-east-1, PHP 8.0, version 21)
        - arn:aws:lambda:us-east-1:534081306603:layer:php-80-fpm:21
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  DemoHttpApi:
    Description: 'Invoke URL for Prod'
    Value: !Sub >-
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
