AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Serverless WordPress texturize function'

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: zip
    Properties:
      FunctionName: wptexturize
      Description: 'Formats titles/links via Lambda'
      CodeUri: .
      Handler: index.php
      Runtime: provided.al2
      Timeout: 30        # API Gateway max timeout is 30s
      MemorySize: 1024   # adjust for PHP performance
      Layers:
        - arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:4
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  DemoHttpApi:
    Description: 'Invoke URL for Prod'
    Value: !Sub >-
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
